# syntax=docker/dockerfile:1

FROM nginx

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY requestment-3 /etc/nginx/html/week-3/requestment-3
COPY requestment-4 /etc/nginx/html/week-3/requestment-4

